ifeq ($(TARGET_BUILD_VARIANT),user)
ALI_CFLAGS += -DALI_USER_BUILD_KERNEL
endif

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
ALI_CFLAGS += -DALISEC_ASEC_SWITCH
endif

$(warning "TARGET_BUILD_VARIANT:$(TARGET_BUILD_VARIANT)")

YUNOS_SECURITY_DIR := aliyun/security
YUNOS_SECURITY_STUB_DIR := $(YUNOS_SECURITY_DIR)/stub/
YUNOS_SECURITY_MODULE_DIR := $(YUNOS_SECURITY_DIR)/module

ALI_INC += -I$(srctree)/$(YUNOS_SECURITY_STUB_DIR)

ALI_CDEFS +=

LINUXINCLUDE    += $(ALI_INC)
KBUILD_CFLAGS   += $(ALI_CFLAGS) $(ALI_CDEFS)

drivers-y += $(YUNOS_SECURITY_STUB_DIR)
include $(srctree)/$(YUNOS_SECURITY_MODULE_DIR)/modules.mk
